# Generated by Django 4.2.7 on 2023-11-15 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumer',
            name='Chemistry',
            field=models.CharField(default=0, max_length=100, verbose_name='Chemistry'),
        ),
        migrations.AddField(
            model_name='consumer',
            name='MCS',
            field=models.CharField(default=0, max_length=100, verbose_name='MCS'),
        ),
        migrations.AddField(
            model_name='consumer',
            name='PSP',
            field=models.CharField(default=0, max_length=100, verbose_name='PSP'),
        ),
        migrations.AddField(
            model_name='consumer',
            name='Physics',
            field=models.CharField(default=0, max_length=100, verbose_name='Physics'),
        ),
        migrations.AddField(
            model_name='consumer',
            name='maths',
            field=models.CharField(default=0, max_length=100, verbose_name='Maths'),
        ),
    ]
