# Generated by Django 4.2.7 on 2023-11-17 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_consumer_chemistry_consumer_mcs_consumer_psp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumer',
            name='adress',
            field=models.TextField(blank=True, null=True, verbose_name='Address'),
        ),
    ]
