# Generated by Django 4.2.7 on 2023-11-17 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_consumer_adress'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumer',
            name='college_department',
            field=models.CharField(default=0, max_length=100, verbose_name='College Department'),
        ),
        migrations.AddField(
            model_name='consumer',
            name='student_semester',
            field=models.CharField(default=0, max_length=10, verbose_name='Student semester'),
        ),
    ]
